### ISSUE TITLE
Custom URL/Web Form Programming - Node 1388

### ISSUE THREAD

**Issue by ucem** [ehodul/universities-colleges-schools#146]
ProgramID needs to be changed to Program.

The value of efr9wr needs to be coded as a parameter for keycode.
I need a value for id.  The id of the lead from your system.
There is only one campus so we don't need to transmit it.  I took the campusID (400101) from their source code, but they received an error message and said " You passed a campusID = 400101.  Not sure how that translates?"
<input type="hidden" name="CampusID" value="400101" class="wpcf7-hidden" />

These are the errors that they received are:

Missing parameter - Program
Missing parameter - id
Missing parameter - key code

Will send requirements via email.

**Comment by ehodul** [comment]
I updated the code as requested and received successful response to my test submission.
I was not sure what to use for 'id' parameter, so I just set it to timestamp of submission.

**Comment by ucem** [comment]
Thanks erika,

I¹m waiting to see if they received it ok.


From:  Erika Hodul <notifications@github.com>
Reply-To:  ehodul/universities-colleges-schools
<reply+00285a2e7eca25483e49821dc03a55c2d14c3f4d63fcf6bc92cf00000001124b82769
2a169ce06c62549@reply.github.com>
Date:  Friday, October 30, 2015 at 11:09 AM
To:  ehodul/universities-colleges-schools
<universities-colleges-schools@noreply.github.com>
Cc:  UCEM Administrator <info@uc-education-marketing.com>
Subject:  Re: [universities-colleges-schools] Custom URL/Web Form
Programming - Node 1388 (#146)


I updated the code as requested and received successful response to my test
submission.
I was not sure what to use for 'id' parameter, so I just set it to timestamp
of submission.


Reply to this email directly or view it on GitHub
<https://github.com/ehodul/universities-colleges-schools/issues/146#issuecom
ment-152620321> .

**Comment by ucem** [comment]
It appears that CampusID appears as a mandatory field and again is transmitted to this school.  I thought Campus ID's in all web forms (Issue 147) were made optional?  

I am getting an error message for leads transmitted which says connection refused and don't know if it has anything to do with CampusID still showing up in the query string>
![screen shot 2015-12-28 at 1 19 48 pm](https://cloud.githubusercontent.com/assets/2644526/12026155/3f1b5a82-ad6b-11e5-9edd-8351e960b7ed.png)

**Comment by ehodul** [comment]
CampusID field is not mandatory, but when there is a webform component with 'CampusID' Field key (as it is in case of Oxford college), then it is added to lead submission. In case of Oxford college though, the campus id (CampusID in 'Custom Lead Form URLs') for Scarborough has no value. This might be a problem. I would suggest either to delete CampusID field from Webform if it is not required, or add a proper id for Scarborough campus in 'Custom Lead Form URLs'.

**Comment by ucem** [comment]
I should have clarified that I had tried taking out the CampusID field and it's still a mandatory option.  I removed Scarborough from the school node, all the program nodes and from the lead form, flushed all caches, cleared my cache and it's still showing up as a mandatory field in the lead form, but no option to select city since it's been taken out.  

In order for the school to show up when someone searches for a specific city, I believe we need to have it added to the school node.  It's strange, because even though the city has been removed, the school still shows up in the list when searching for the city.

![screen shot 2015-12-29 at 10 37 15 am](https://cloud.githubusercontent.com/assets/2644526/12039867/040465ca-ae19-11e5-8344-fb8a4e86d7a8.png)

**Comment by ehodul** [comment]
I did some database cleanup, deleted the location instance for one of the programs for Oxford college, there is no Campus drop down anymore.

**Comment by ucem** [comment]
I noticed you were doing some testing and a timed out error occurred.  They might be having errors on their end and am waiting to hear back from them.

Which of the programs still had a location?  I thought I had deleted them all?

Also, if we add the location to the school node, will this issue come up again, or is it independent of the web form?

**Comment by ucem** [comment]
Sorry to be a pain about this but as soon as I added the city to location back to the school node, so that it can be found under a location search, the CampusID was automatically entered into the web form. 

If a location is not added to the school node, then the school does is not listed in the search-by-city/Scarborough and not adding location to the programs results in no programs listed for the school.  
![screen shot 2015-12-29 at 2 11 50 pm](https://cloud.githubusercontent.com/assets/2644526/12043149/d699515e-ae36-11e5-85b7-6a18c3c69cca.png)

Unfortunately everything is tied together, what is the best solution to fix this?

**Comment by ehodul** [comment]
If there is a location, the CampusID is added. If there is no location, it is not added. Yes, everything is tied together. I am trying to figure out what to do here. Perhaps we should only display campuses that are specified for programs and not display campuses entered for school?

**Comment by ucem** [comment]
So if we display campuses for programs only, and a search is done (search-by-province-state) or search-by-city/ will the school and programs be shown?

**Comment by ehodul** [comment]
It is confusing right now. Some of the searches return results based on school location. Some of the searches return results by program location.
For example this search returns result for school location:
http://www.universities-colleges-schools.com/search-by-city/Scarborough
- however, it then states that "There are no programs listed for this location".

**Comment by ucem** [comment]
Yes unfortunately, when i removed location from all the programs for this school,no programs at this campus location are listed. 
Suggestions?

**Comment by ehodul** [comment]
Can we add the location back for the programs? We can remove the CampusID from the submission (let's specify NA in the  'CampusID Field name' in 'Custom Lead Form URLs') if needed.

**Comment by ucem** [comment]
Yes, I can add the locations back.  

Does removing CampusID, only apply to this school?  And does your explanation in issue 147 still hold true then?

**Comment by ehodul** [comment]
We will show CampusID on the form (it will be preselected with 'Scarborough') and delete the CampusID from submission (for this school and all other schools where 'NA' is in the 'CampusID Field name' in 'Custom Lead Form URLs'). My explanation in issue #147 is true, the CampusID is optional for the submission form. Unfortunately it is necessary for the search by location.
